package.json, static/src/sass/_pepo.common.scss, static/src/sass/pepo.all.scss
=> :rocket: Add bourbon and bourbon-neat.

package.json
=> :wrench: Fix bourbon dependencies.

static/src/app/templates/feed.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss
=> :necktie: Update tweet with new layuot.

static/src/app/pepo.js
Поправил путь в роутинге, теперь ссылки на профиль будут выглядеть так:
`/profile/me`
`/profile/anotheruser`
=> :wrench: Var for profile path.

static/src/app/templates/feed.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss
Добавил инпут для нового твита на странице ленты.
=> :rocket: Add text input for new pep.

app.js, lib/patch-plugin.js, models/user.js, routes/user.js
Роуты для авторизованного пользователя:
```
GET /api/user - информация о пользователе
PATCH /api/user - изменение пользователя
DELETE /api/user - удаление пользователя
```
=> User routes

static/src/app/templates/users.html
Заменил `src` в путях аватарок на `ng-src`.
=> :wrench: Fix avatar paths.

static/src/app/templates/login.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.users.scss
Добавил мобильный вид для страницы users.
=> :rocket: Mobile layout for users page.

static/src/app/controllers/editProfileCtrl.js, static/src/app/templates/edit-profile.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.edit-profile.scss, static/src/sass/pepo.all.scss
Сделал страницу `edit-profile` на основе общего дизайна.
=> :rocket: New edit-profile page.

static/src/app/controllers/editProfileCtrl.js, static/src/app/controllers/feedCtrl.js, static/src/app/controllers/loginCtrl.js, static/src/app/templates/edit-profile.html, static/src/app/templates/feed.html, static/src/app/templates/login.html
Добавил редирект залогиненого юзера.
Если новый юзер, то редиректим на `/edit-profile`
Если старый юзер, то редиректим на `/feed`
=> :rocket: Redirect logged user with separation new and old users.

static/src/sass/_pepo.common.scss
Редактировал css class page-conteiner  в  блоке авторизации
=> Edit page conteiner.

static/src/app/controllers/singlePepCtrl.js, static/src/app/pepo.js, static/src/app/services/mockTweets.js, static/src/app/templates/single-pep.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.header.scss, static/src/sass/_pepo.single-tweet.scss, static/src/sass/pepo.all.scss
Добавил пототипную страницу одного пепа.
=> Single pep page

static/src/app/templates/login.html, static/src/sass/_pepo.chooselogin.scss
Поправил страницу логина на моб ширине.
=> :wrench: Login page mobile layout.

static/src/app/services/mockTweets.js, static/src/app/templates/feed.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss
Поправил мобильную верстку для страницы `/feed`
=> Feed mobile

static/src/app/controllers/editProfileCtrl.js, static/src/app/templates/edit-profile.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.edit-profile.scss
Добавил cancel кнопку на страницу `edit-profile`.
=> :wrench: Add cancel btn on edit-profile.

static/src/sass/_pepo.users.scss
Добавил мобильную верстку на странице `users`.
=> :wrench: Mobile layout for users-page.

static/src/sass/_pepo.single-tweet.scss
Ограничил максимальную шрину для логина, если логин длиннее то обрезаем его с точками вконце.
=> :wrench: Restrict user login max-width.

static/src/app/templates/feed.html, static/src/img/icon-add.svg, static/src/img/icon-add__active.svg, static/src/sass/_pepo.feed.scss
Добавил кнопку для подгрузки дополнительных пепов.
=> :rocket: Add load-more-peps btn.

app.js, models/user.js, routes/user.js, routes/users.js
```GET /api/users``` - список пользователей
```GET /api/users/:username``` - информация о пользователе
```GET /api/users/:username/following``` - список пользователей, на которых подписан пользователь
```GET /api/users/:username/followers``` - список пользователей, которые подписаны на пользователя
```POST /api/users/:username/follow``` - подписка на пользователя
```DELETE /api/users/:username/follow``` - отписка от пользователя
=> Users routes

app.js, models/status.js, routes/statuses.js, routes/user-statuses.js, routes/users.js
```GET /api/statuses``` - список всех твитов
```POST /api/statuses``` - создание твита
```GET /api/statuses/:id``` - твит
```PATCH /api/statuses/:id``` - изменение твита
```DELETE /api/statuses/:id``` - удаление твита
```GET /api/users/:id/statuses``` - твиты пользователя
=> Statuses routes

static/src/app/controllers/myProfileCtrl.js, static/src/app/templates/my-profile.html, static/src/sass/_pepo.profile.scss
Добавил странитцу юзера и твиты
=> add user profile

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/pepo.all.scss
Добавлена форма в модальном окне при ответе на пеп.
Добавлено модальное окно для подтверждения удаления пепа.
=> Answer form

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html
Создал возможность удаления пепа, по индексу в тестовом массиве.
=> delleting peps by index in array

static/src/app/controllers/feedCtrl.js, static/src/app/services/pepApi.js, static/src/app/templates/feed.html
Добавил сохранение пепа на сервере.
Добавил загрузку пепов с сервера на странице `feed`
=> :rocket: Save/load peps.

static/src/app/controllers/feedCtrl.js, static/src/app/services/pepApi.js, static/src/app/templates/feed.html
Добавлена возможность удаления пепов, со связью с сервером и отслеживанием ошибки.
=> deleting peps with api

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html
Закрытие модалки после отправки пепа.
Проверка статуса в промисе.
=> Save pep on server

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html, static/src/sass/_pepo.feed.scss
Добавил подгрузку дополнительных пепов по клику на кнопке под последним пепом.
=> Pep answer server

static/src/app/controllers/singlePepCtrl.js, static/src/app/services/pepApi.js, static/src/app/templates/feed.html, static/src/app/templates/single-pep.html
По клику на дату переходим на страницу определенного пепа.
Данные пепа грузятся с сервера по id.
=> Single pep server

static/src/app/controllers/editProfileCtrl.js, static/src/app/controllers/feedCtrl.js, static/src/app/directives/avatarLoad.js, static/src/app/services/multipartForm.js, static/src/app/templates/edit-profile.html
Добавил сервис для multipart загрузки аватарки, ждем бекенд для этой функциональности.
=> :rocket: Avatar multipart loading service.

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html, static/src/sass/_pepo.edit-pep.scss, static/src/sass/_pepo.feed.scss
Добавил анимацию на фон пепа при его редактировании
Добавил ховер эффекты на кнопки панели редактирования
Изменил ховер эффекты панели действий на пепом( теперь при наведении они увеличиваються, а при нажатии проваливаются - так прикольнее)
=> Editing animation

static/src/app/directives/header.js, static/src/app/templates/modules/header.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.slide-menu.scss
Теперь при клике на иконку добавления твитта происходит событие открытие модалки  для добавления нового твитта.
=> New pep action in header.

static/src/app/controllers/feedCtrl.js, static/src/app/controllers/singlePepCtrl.js, static/src/app/directives/header.js, static/src/app/templates/feed.html, static/src/app/templates/modules/header.html, static/src/app/templates/single-pep.html
Пофиксил добавление пепа на странице юзера.
=> Add pep on mypage

static/src/app/controllers/myProfileCtrl.js, static/src/app/templates/feed.html, static/src/app/templates/my-profile.html, static/src/sass/_pepo.edit-pep.scss, static/src/sass/_pepo.slide-menu.scss
Сделал загрузку данных реального пользователя в страницу my-profile
Багфиксы slide-menu
Замена интупов на дивы при редактировании и удалении пепа.
=> User page load data

static/src/app/templates/my-profile.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.edit-pep.scss, static/src/sass/_pepo.profile.scss
На странице юзера теперь грузиться аватарка
Убран лишний маргин у блока пепов
Изменен цвет при ховере у кнопки отменить
=> bugfixes user profile (img, margin, colorLightGray__hover)

static/src/app/controllers/feedCtrl.js, static/src/app/templates/feed.html, static/src/app/templates/my-profile.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.header.scss, static/src/sass/_pepo.profile.scss
1. Поправил форму ответа на пеп.
2. Выпилил лишний `<section>` на странице юзера.
=> Feed fixes

static/src/app/controllers/usersCtrl.js, static/src/app/services/usersApi.js, static/src/sass/_pepo.answer-form.scss
Заменил на странице юзеров моковский контент на актуальный
=> try to load real users

index.html
=> :wrench: Fix iphone autozoom.

static/src/app/controllers/feedCtrl.js, static/src/app/directives/header.js, static/src/app/templates/feed.html, static/src/app/templates/modules/header.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.slide-menu.scss
=> :wrench: Fix open menu performance.

static/src/app/templates/feed.html, static/src/app/templates/my-profile.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.profile.scss
Исправил отображение пепов в модальных окнах на странице feed
Поправил кнопку подписки с помощью медиа запросов на странице my-profile.
=> Modal bugfix

models/user.js, routes/users.js
Добавил поле ```description``` пользователю
=> Add description to user

static/src/app/controllers/editProfileCtrl.js, static/src/app/controllers/feedCtrl.js, static/src/app/controllers/myProfileCtrl.js, static/src/app/controllers/singlePepCtrl.js, static/src/app/controllers/usersCtrl.js, static/src/app/directives/header.js, static/src/app/services/feedApi.js, static/src/app/services/usersApi.js, static/src/app/templates/modules/header.html, static/src/app/templates/my-profile.html, static/src/app/templates/users.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.header.scss, static/src/sass/_pepo.profile.scss, static/src/sass/_pepo.users.scss
Добавлена функциональность подписки/отписки на пользователя.
=> User subscribe

static/src/app/controllers/editProfileCtrl.js, static/src/app/templates/my-profile.html
Добавлена возможность редактирования description пользователя.
=> :wrench: Edit user description.

config.js, routes/user.js
Костыль для отключения sharp'а.
Чтобы отключить sharp, добавь в файл .env:
```bash
SHARP_DISABLED="yes"
```
=> Add ability to disable sharp module

package.json, static/src/app/controllers/usersCtrl.js, static/src/app/templates/users.html
поиск юзеров через Api
вызов debounce при изменении поля ввода
=> search user with api

config.js, static/src/app/controllers/editProfileCtrl.js, static/src/app/directives/avatarLoad.js
=> :wrench: Fix reg paths.

static/src/app/controllers/myProfileCtrl.js, static/src/app/templates/my-profile.html, static/src/sass/_pepo.profile.scss
Создание анимированного перемещения ползунка на info-item в странице профиля
=> create animation for info items in my-profile

static/src/app/directives/header.js, static/src/app/templates/choose-login.html, static/src/app/templates/login.html, static/src/app/templates/modules/header.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.inf-block-newpeps.scss, static/src/sass/_pepo.single-tweet.scss, static/src/sass/pepo.all.scss
Создан блок с информацией о новых пепах , а так же теги <button>и <input> были заменены на <div>
=> Create inf block new paps.

static/src/app/controllers/editProfileCtrl.js, static/src/app/directives/avatarLoad.js, static/src/app/directives/header.js, static/src/app/pepo.js, static/src/app/templates/edit-profile.html, static/src/app/templates/modules/header.html, static/src/sass/_pepo.edit-profile.scss
Добавлено превью при загрузки аватарки
=> Edit profile

static/src/app/controllers/myProfileCtrl.js, static/src/app/services/usersApi.js, static/src/app/templates/my-profile.html, static/src/sass/_pepo.profile.scss
Подсчет количества читаемых и читателей на странице профиля
=> Info counts profile

static/src/app/directives/modalAnswer.js, static/src/app/templates/single-pep.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.inf-block-newpeps.scss, static/src/sass/_pepo.single-tweet.scss
Поправил размеры шрифтов и отступы на странице пепа.
=> :wrench: Single pep refactor.

config.js, lib/picture-utils.js, models/user.js, passport.js, routes/user.js
Получаем аватарку из профиля соц. сети
=> Avatar from social

index.html, static/src/app/pepo.js, static/src/app/services/config-client.js
Вынес конфиги для клиента в сервис ангуляра.
=> :wrench: Fix client config.

gulpfile.js, package.json, static/src/app/controllers/feedCtrl.js, static/src/app/directives/header.js, static/src/app/pepo.js, static/src/app/templates/modules/header.html, static/src/sass/_pepo.header.scss
Добавлена плавный скролл при создании и редактировании Пепов
=> Rustem1022.scroll mod

static/src/sass/_pepo.slide-menu.scss
Фикс моб меню, выпилил трансформ, на андройде не работает.
=> :wrench: Replace transform with right for show mob nav.

static/src/app/controllers/myProfileCtrl.js, static/src/app/templates/my-profile.html, static/src/sass/_pepo.profile.scss, static/src/sass/_pepo.users.scss
Сделал адаптивной кнопку "Читаю", по аналогии с кнопкой "+Читать"
Исправил баг с отображением подписки на странице пользователя
=> Dyadya jora.follow button

static/src/app/directives/modalAnswer.js, static/src/app/directives/modalDel.js, static/src/app/templates/modules/modalAnswer.html, static/src/app/templates/modules/modalDel.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.users.scss
Редактирование модальных окон с формами ответа и удаления
=> Dyadya jora.bugfix modal

static/src/app/controllers/usersCtrl.js, static/src/app/templates/users.html, static/src/sass/_pepo.users.scss
Добавлена пагинация для страницы `/users`
=> :rocket: Users pagination.

gulpfile.js, package.json, static/src/app/pepo.js, static/src/app/templates/feed.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.single-tweet.scss
=> :rocket: Time ago dirrective.

static/src/app/templates/my-profile.html
Timeago directive on user page.
=> :rocket: Timeago directive on user page.

app.js, bin/www, config.js, gulpfile.js, package.json, routes/statuses/index.js
Присылает информацию о количестве новых пепов.
На фронте:
```javascript
var socket = io.connect();
socket.on('statuses', function(statuses) {
// statuses.count - количество новых пепов
// statuses.data - массив с информацией о пепах
// в формате { owner: 'user-id', id: 'status-id' }
});
```
=> Add sockets

static/src/app/controllers/myProfileCtrl.js, static/src/app/controllers/singlePepCtrl.js, static/src/app/directives/modalAnswer.js, static/src/app/directives/modalDel.js, static/src/app/templates/modules/modalDel.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.emoji.scss, static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.single-tweet.scss
обеспечил работу удаления/редактирования/ответа на странице пепа
багфикс с отображением даты создания при ответе на пеп.
добавление currentlocation на страницу профиля и страницу пепа.
багфикс модалок.
=> Dyadya jora.single pep actions

static/src/app/templates/my-profile.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.profile.scss, static/src/sass/_pepo.single-tweet.scss
Добавил карту на страницу пепа и на страницу юзера.
=> Map on single pep

static/src/app/controllers/feedCtrl.js, static/src/app/controllers/myProfileCtrl.js, static/src/app/controllers/singlePepCtrl.js, static/src/app/directives/modalAnswer.js, static/src/app/templates/feed.html, static/src/app/templates/my-profile.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.edit-pep.scss, static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.single-tweet.scss
Добавил смайлы при ответе на пеп на странице профиля, feed, singlePep.
Багфикс с отображением смайлов(переменную отображения делать false  перед открытием формы\блока)
=> Dyadya jora.emoji anywhere

static/src/app/controllers/feedCtrl.js, static/src/app/directives/header.js, static/src/app/directives/limitto.js, static/src/app/directives/modalAnswer.js, static/src/app/templates/feed.html, static/src/app/templates/modules/modalAnswer.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.header.scss
Убрали  возможность удаления чужих твиттов.
=> Validation form

static/src/app/controllers/feedCtrl.js, static/src/app/controllers/myProfileCtrl.js, static/src/app/controllers/usersCtrl.js, static/src/app/services/feedApi.js, static/src/app/services/usersApi.js, static/src/app/templates/feed.html, static/src/app/templates/my-profile.html
Переписал обращения к апи с учетом нового формата возвращаемых данных.
=> Userpage pagination

static/src/app/directives/header.js, static/src/app/directives/modalAnswer.js, static/src/app/templates/modules/header.html, static/src/app/templates/modules/modalAnswer.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.emoji.scss
Добавление иконки загрузки фотографий и в модалку ответа.
Багфиксы с кнопкой, расположением смайлов и счетчика количества символов, очищение textarea при закрытии модалок
=> Dyadya jora.modal answer upload ico

static/src/app/directives/header.js, static/src/app/templates/modules/header.html
Переход по ссылкам в слайдбаре
Bugfixes: модалка добавления нового пепа - вертикальная прокрутка на мобильных
=> Dyadya jora.bugfixes all

static/src/app/templates/feed.html, static/src/sass/_pepo.feed.scss
=> Dyadya jora.links preview

static/src/app/directives/header.js, static/src/app/templates/modules/header.html, static/src/app/templates/modules/modalAnswer.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.emoji.scss, static/src/sass/_pepo.header.scss
Fix update avatar on new pep add location and date
=> add location date in new pep

static/src/app/templates/my-profile.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.single-tweet.scss
Bugfix исправил белые ссылки #129 
Добавил превью ссылок на странице профиля и на стрнице отдельного пепа(для всех в иерархии)
=> Dyadya jora.link preview next

static/src/app/controllers/feedCtrl.js, static/src/app/controllers/myProfileCtrl.js, static/src/app/controllers/singlePepCtrl.js, static/src/app/directives/header.js, static/src/app/directives/limitto.js, static/src/app/directives/modalAnswer.js, static/src/app/templates/feed.html, static/src/app/templates/modules/header.html, static/src/app/templates/modules/modalAnswer.html, static/src/app/templates/modules/modalDel.html, static/src/app/templates/my-profile.html, static/src/app/templates/single-pep.html, static/src/sass/_pepo.answer-form.scss, static/src/sass/_pepo.feed.scss
Ограничение длины пепа в 140 символов не считая ссылок #132 
* изменил директиву limitto для отслеживания ссылок
* везде где можно добавить или редактировать пеп добавлено ограничение максимальной длины в 140 символов
=> Dyadya jora.max length 140

static/src/app/directives/header.js, static/src/app/directives/modalAnswer.js
Исправил баг для предыдущего ПР, ответы и новые пепы теперь добавляются.
=> fix: adding new pep and answer working

static/src/app/controllers/editProfileCtrl.js, static/src/app/templates/edit-profile.html, static/src/sass/_pepo.answer-form.scss
#131  Создал всплывающие сообщения для страницы edit-page, которые оповещают об ошибке или удачном сохранении файла
=> Message edit

static/src/sass/_pepo.feed.scss, static/src/sass/_pepo.single-tweet.scss
=> word break for peps

.eslintignore, .eslintrc, package.json, static/src/app/.eslintrc
#141
Запуск JavaScript линтера фронтенда:
```
npm run lint:app -s
```
Запуск JavaScript линтера бекенда:
```
npm run lint:server -s
```
=> Add javascript linter

static/src/app/controllers/feedCtrl.js, static/src/app/directives/header.js, static/src/app/directives/modalAnswer.js, static/src/app/directives/modalDel.js, static/src/app/templates/feed.html, static/src/app/templates/my-profile.html, static/src/sass/_pepo.common.scss, static/src/sass/_pepo.feed.scss
При отсутствии пепов на странице \ в ленте теперь будут отображаться блоки с информацией
* блок с информацией для feed
* блок с информацией для текущего пользователя
* блок с информацией для страничек других пользователей
* bugfix - подгрузка количества пепов на myProfile при их изменении
=> Block zero pep

app.js, lib/file-storage.js, middleware/satellizer-adapter.js, models/user.js, routes/feed.js, routes/statuses/children.js, routes/statuses/index.js, routes/user.js, routes/users/statuses.js
=> Cleanup server js

static/src/app/controllers/feedCtrl.js, static/src/app/directives/header.js, static/src/app/templates/modules/header.html, static/src/sass/_pepo.inf-block-newpeps.scss
Добавил вендорные префиксы для inf-block
Пофиксил счетчик новых пепов
Новые пепы добавляются в верех ленты
=> socket bugfix

static/src/app/controllers/editProfileCtrl.js, static/src/app/templates/edit-profile.html
Добавил модалку с приветствием и указанием выбрать логин а странице редактирования профиля при первом входе в систему
=> first welcome modal at editProfile page
